services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
    - .env
    ports:
    - ${APP_PORT}:${APP_PORT}
    expose:
    - ${APP_PORT}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 1s
      timeout: 2s
      retries: 5
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

volumes:
  pg_data: